### ISSUE TITLE
Create Staking Pool with more than one reward token

### ISSUE THREAD

**Issue by marleymarl** [idexo/ido-contracts#118]
Projects by idexo have the likelihood of needing more than one reward token (e.g. usdt or usdc and the project token). Since the project token, if it is created, is likely to be created after the deployment of the staking contract, there needs to be a function to add a new reward token and likely an array of reward tokens. This complicates the functions for depositing rewards, adding claimable rewards and claiming rewards in that they need to specify the reward token, likely by specifying the index of the reward token array.

**Comment by Dluks82** [comment]
According to the need and with the guidelines given, the approach used was to include mapping with the address of the reward token as a key pointing to the corresponding IERC20 interface.
It will be fed the first reward token in the contract build, where it should receive the token address.
Also included is a function to add new reward tokens that take the address as a parameter.
Consequently, the depositReward, addClaimableReward, addClaimableRewards and ClaimReward functions must pass the 0x address of the reward token as a parameter.

https://github.com/idexo/ido-contracts/pull/119
