### ISSUE TITLE
Time limited (deposits) stake pool post min stake reached

### ISSUE THREAD

**Issue by marleymarl** [idexo/ido-contracts#145]
This is a stake pool that allows for multiple rewards and has the following special characteristics: 

* A minimum total pool stake amount (set in the constructor) that is required to change its state to time limited (i.e. initial state could be unlimited and when min stake it reached then state is changed to timelimited). Example: this min total pool stake amount could be 500K tokens (of the deposit token)
* The time limit in milliseconds (set in the constructor) that becomes the remaining time to stake once state is changed to timelimited
* After this time limit expires it is no longer possible to stake, i.e. state changes to stakedisabled and in that state staking will fail.

**Comment by Dluks82** [comment]
Just a curiosity, after the minimum set amount reached and the counter for the staking deadline start:
- Can the amounts deposited before be withdrawn?
- Will there be any blocking time for the withdrawal of deposits after the end of the deadline for deposit?

A single person can deposit the minimum amount by starting the counter and minutes later withdraw the deposit

**Comment by marleymarl** [comment]
Hmmm good point. Let's set it to reset the state to unlimited if total staked ever falls below the minimum (this check can happen within the withdraw function).
