### ISSUE TITLE
Create payment contract that enables payment and product tracking

### ISSUE THREAD

**Issue by marleymarl** [idexo/ido-contracts#148]
The contract should allow for initial payment token to be specified in the constructor, however it should make it possible to add other payment tokens in an array of them in a separate function. This should enable the creation of a product with a specific price in specified payment token. There should be a purchase function and there should be a way to lookup addresses that have purchased the specific product. Could also be a simpler method to look up one address and see if it hasPurchased a product.

**Comment by Dluks82** [comment]
we must have
* a array[paymentToken] to store the different payment tokens;
* a array[Product] to store the products:
- productId = "IDO_COURSE"
- productName = "Idexo Course"
- paymentToken = "0x" // CRED or other
- price = "1000"
* a mapping to store the products purchased by users:
- address => products[]
