### ISSUE TITLE
New IGSP Staking Contract

### ISSUE THREAD

**Issue by marleymarl** [idexo/ido-contracts#152]
Add a stakeType variable (quarterly, annual, tri-annual) that gets associated with a tokenId

getStakeType(tokenId) returns its type

set withdrawal lock timestamps through presents inside functions

* depositQuarterly sets timestamp as 91.25 days from deposit block.timestamp
* depositAnnual sets timestamp 365 days from deposit block.timestamp
* depositTriAnnual sets timestamp 1095 days from deposit block.timestamp

addStake(tokenId) allows a user to add more token to their existing stake, with no minimum amount to add

setCompounding(tokenId) is set by owner of tokenId and compounding is a boolean variable associated with the tokenId
unsetCompounding(tokenId) can be called to change the value of compounding to false
isCompounding(tokenId) returns true or false
compoundingIds() returns the array of tokenIds that are compounding

**Comment by Dluks82** [comment]
new requirement:

- should also allow topup deposits on a tokenid to be done by operator in addition to tokenid holder. Only additions of course not withdrawals

**Comment by Dluks82** [comment]
```
    struct Stake {
        uint256 amount;
        uint256 multiplier;
        string stakeType;
        uint256 depositedAt;
        uint256 lockedUntil;
        bool compounding;
    }
```

`addStakeType(string memory typeName, uint256 lockedInDays)`
- The contract owner can create new periods, eg: MONTHLY: 30, QUARTERLY: 90

`function deposit(uint256 amount, string memory depositType, bool autoCompounding) `
- creates a new locked deposit within the stakeType period

`function setCompounding(uint256 tokenId, bool compounding)`
- Allows stake owner to change the autocompound variable

`function addStake(uint256 stakeId, uint256 amount)`
- Once the deposit is unlocked for withdrawals, the owner of the contract or stakeToken can increase the amount to later make a reLock

`function reLockStake(uint256 stakeId, string memory depositType, bool autoCompounding)`
- Allows the owner to lock a stakeToken that is already unlocked for withdrawals

`function isCompounding(uint256 stakeId)`
- Checks if a stakeToken is autocompounding

`function getCompoundingIds()`
- Returns an array of autocompounding stakeTokens

**Comment by marleymarl** [comment]
function addStake(uint256 stakeId, uint256 amount)

"Once the deposit is unlocked for withdrawals, the owner of the contract or stakeToken can increase the amount to later make a reLock"

No need for it to be unlocked. This can be added to anytime (event while locked). Should be owner, operator or staketoken holder who can do this.

**Comment by Dluks82** [comment]
New contract deployed
