### ISSUE TITLE
Add Unit Test coverage

### ISSUE THREAD

**Issue by heldersepu** [idexo/ido-contracts#40]
https://medium.com/edgefund/testing-and-code-coverage-of-solidity-smart-contracts-660cb6291701

Looks like using coveralls we can get some nice inside into how much of our code is covered by unit tests

**Comment by coozebra** [comment]
Okay, I will use this tool for unit testing

**Comment by heldersepu** [comment]
Sample integration with github actions:
https://github.com/coverallsapp/github-action

**Comment by heldersepu** [comment]
Ran into error:
`RuntimeError: memory access out of bounds`
https://github.com/idexo/ido-contracts/runs/4142649707?check_suite_focus=true#step:6:4407

might be better to look into what OpenZeppelin is using:
https://github.com/OpenZeppelin/openzeppelin-contracts
